'use client';

import { useEffect } from 'react';

export default function TermsAndConditions() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 to-slate-800 text-slate-100">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-pink-600 py-12 px-4">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms & Conditions</h1>
          <p className="text-lg opacity-90">Last updated: June 2026</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-slate-800 rounded-xl p-8 shadow-2xl space-y-8">
          
          {/* Section 1 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">1. Electronic Record</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">2. Publication & Compliance</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <span className="text-purple-400">https://ppsky4.vercel.app/</span> {`('Website')`}, including the related mobile site and mobile application (hereinafter referred to as {`'Platform'`}).
            </p>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">3. Platform Ownership</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              The Platform is owned by <span className="font-semibold">8459210421</span>, a company incorporated under the Companies Act, 1956 with its registered office at <span className="font-semibold">Farshi road, Amalner, Jalgaon</span> (hereinafter referred to as {`'Platform Owner', 'we', 'us', 'our'`}).
            </p>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">4. Binding Nature of Terms</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              Your use of the Platform and services and tools are governed by the following terms and conditions ({`"Terms of Use"`}) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction.
            </p>
            <p className="text-slate-300 leading-relaxed mb-4">
              By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
            </p>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">5. User Definition</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              For the purpose of these Terms of Use, wherever the context so requires {`'you', 'your' or 'user'`} shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
            </p>
          </section>

          {/* Important Notice */}
          <div className="bg-purple-900 border-l-4 border-purple-400 p-6 rounded-lg my-8">
            <p className="text-white font-bold text-lg mb-2">⚠️ IMPORTANT NOTICE</p>
            <p className="text-slate-200">
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE. PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
            </p>
          </div>

          {/* Section 6 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">6. Terms of Use</h2>
            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-semibold text-pink-400 mb-2">6.1 Accurate Information</h3>
                <p className="text-slate-300">
                  To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-pink-400 mb-2">6.2 No Warranty</h3>
                <p className="text-slate-300">
                  Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-pink-400 mb-2">6.3 Use at Your Own Risk</h3>
                <p className="text-slate-300">
                  Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-pink-400 mb-2">6.4 Intellectual Property Rights</h3>
                <p className="text-slate-300">
                  The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents include and are not limited to the design, layout, look and graphics.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-pink-400 mb-2">6.5 Unauthorized Use</h3>
                <p className="text-slate-300">
                  You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-pink-400 mb-2">6.6 Payment Charges</h3>
                <p className="text-slate-300">
                  You agree to pay us the charges associated with availing the Services.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-pink-400 mb-2">6.7 Lawful Use</h3>
                <p className="text-slate-300">
                  You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-pink-400 mb-2">6.8 Third-Party Links</h3>
                <p className="text-slate-300">
                  You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-pink-400 mb-2">6.9 Binding Contract</h3>
                <p className="text-slate-300">
                  You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
                </p>
              </div>
            </div>
          </section>

          {/* Section 7 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">7. Indemnification</h2>
            <p className="text-slate-300 leading-relaxed">
              You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable {`attorney's`} fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
            </p>
          </section>

          {/* Section 8 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">8. Force Majeure</h2>
            <p className="text-slate-300 leading-relaxed">
              Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
            </p>
          </section>

          {/* Section 9 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">9. Governing Law</h2>
            <p className="text-slate-300 leading-relaxed">
              These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
            </p>
          </section>

          {/* Section 10 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">10. Jurisdiction</h2>
            <p className="text-slate-300 leading-relaxed">
              All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in India.
            </p>
          </section>

          {/* Section 11 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">11. Contact Information</h2>
            <p className="text-slate-300 leading-relaxed mb-4">
              All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
            </p>
            <div className="bg-slate-700 p-4 rounded-lg">
              <p className="text-slate-300"><span className="font-semibold">Company:</span> 8459210421</p>
              <p className="text-slate-300"><span className="font-semibold">Address:</span> Farshi road, Amalner, Jalgaon</p>
              <p className="text-slate-300"><span className="font-semibold">Hours:</span> Monday - Friday (9:00 - 18:00)</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
